server:
  port: 8012
spring:
  application:
    name: king-rabbitmq-consume-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.92.132:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  rabbitmq:
    host: 192.168.92.132
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        default-requeue-rejected: false
  boot:
    admin:
      client:
        url: http://localhost:8014
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
