server:
  port: 8021
spring:
  application:
    name: king-gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.100:8848
    gateway:
      routes:
        - id: king-user-service-gateway
          uri: lb://king-user-service
          predicates:
            - Path=/user/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000