server:
  port: 8027
spring:
  application:
    name: king-dubbo-consumer-service
dubbo:
  application:
    name: king-dubbo-consumer-service
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.31.100:2181
    timeout: 20000
